workflows:
  android-workflow:
    name: Android Build

    environment:
      flutter: stable

    scripts:
      - cd app
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk