import 'package:flutter/material.dart';
import 'provider_setup_screen.dart';
class ProviderDashboardScreen extends StatefulWidget{ const ProviderDashboardScreen({super.key}); @override State<ProviderDashboardScreen> createState()=> _ProviderDashboardScreenState(); }
class _ProviderDashboardScreenState extends State<ProviderDashboardScreen>{
  bool online=true;
  @override
  Widget build(BuildContext context){ return Scaffold(appBar: AppBar(title: Text('Provider Dashboard')), body: Padding(padding: EdgeInsets.all(16), child: Column(children: [Container(padding: EdgeInsets.all(16), decoration: BoxDecoration(color: online? Colors.green[50]: Colors.red[50], borderRadius: BorderRadius.circular(12)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(online? 'Online':'Offline', style: TextStyle(fontWeight: FontWeight.bold)), Switch(value: online, onChanged: (v)=> setState(()=> online=v))])), SizedBox(height: 20), Card(child: ListTile(title: Text('New Request - Ahmed'), subtitle: Text('Lahore - Plumber'), trailing: ElevatedButton(onPressed: (){}, child: Text('Accept'))))])), floatingActionButton: FloatingActionButton.extended(onPressed: ()=> Navigator.push(context, MaterialPageRoute(builder: (_)=> const ProviderSetupScreen())), label: Text('Edit Profile'), icon: Icon(Icons.edit))); }
}
class ProviderSetupScreen extends StatelessWidget{ const ProviderSetupScreen({super.key}); @override Widget build(BuildContext context){ return Scaffold(appBar: AppBar(title: Text('Edit Profile')), body: Padding(padding: EdgeInsets.all(16), child: Column(children: [TextField(decoration: InputDecoration(labelText: 'Category', border: OutlineInputBorder())), SizedBox(height: 12), TextField(decoration: InputDecoration(labelText: 'City', border: OutlineInputBorder())), SizedBox(height: 12), TextField(decoration: InputDecoration(labelText: 'Experience', border: OutlineInputBorder())), SizedBox(height: 20), ElevatedButton(onPressed: ()=> Navigator.pop(context), child: Text('Save'))]))); } }
